#!/usr/bin/env python3
"""Atheris fuzz harness for Pyverilog (target: fuzz-log).

Exercises the PLY-based Verilog HDL parser (pyverilog.vparser.parser) on
arbitrary text input. Atheris instruments the imported pyverilog modules so
libFuzzer gets coverage feedback.

The LALR tables are pre-generated by mayhem/build.sh into a fixed directory
(the commit image is mounted read-only during coverage collection, so the
parser must never regenerate tables at run time).

Run modes (driven by the compiled launcher `pyverilog_fuzzer` / `-standalone`):
  * fuzzing      — `python3 fuzz_log.py [libFuzzer args]`
  * single input — `python3 fuzz_log.py <file>` (libFuzzer runs it once)
"""
import os
import sys

import atheris

import fuzz_helpers

with atheris.instrument_imports(include=['pyverilog']):
    from pyverilog.vparser.parser import VerilogParser, ParseError

PLY_TABLES = os.environ.get('PLY_TABLES_DIR', '/opt/toolchains/python/plytables')

parser = VerilogParser(outputdir=PLY_TABLES, debug=False)


@atheris.instrument_func
def TestOneInput(data):
    fdp = fuzz_helpers.EnhancedFuzzedDataProvider(data)
    try:
        parser.parse(fdp.ConsumeRemainingString())
    except ParseError:
        return -1


def main():
    atheris.Setup(sys.argv, TestOneInput)
    atheris.Fuzz()


if __name__ == '__main__':
    main()
